In [3]:
"""
print() function
"""

print("Hello World!")
print(100)
pi = 3.14
print(pi)

Hello World!
100
3.14


In [4]:
"""
asd
"""

my_name = "lee"
age = 23
my_email = "hamgame3@hs.ac.kr"


In [5]:
"""
Data Type: Integer
"""

value = 10
my_Phone = 2
my_book = 27

In [6]:
"""Data Type: Real Number"""

PI = 3.14
my_tall = 173.4
gold_price = 67502.96


In [9]:
"""
Data Type: String
"""
favorite_company = 'SamSung'
favorite_food = 'pasta'
favorite_carbrand = 'BMW'

print(favorite_company)
print(favorite_food)
print(favorite_carbrand)

print(favorite_company + favorite_food +favorite_carbrand)


SamSung
pasta
BMW
SamSungpastaBMW


In [8]:
"""
Exception Handling
"""

x = 1
try:
    print(y)
    print(x)

except:
    print("Error")
    
print("continue")

Error
continue


In [4]:
"""
List
"""
primes = [2, 3, 5, 7, 11, 11] #중복을 허용한다.
print(primes)
# 리스트 객체 초기화
none_list = []
print(none_list)

[2, 3, 5, 7, 11, 11]
[]


In [7]:
"""
Multiple different data type
"""
# 여러 데이터 타입의 아이템을 포함할 수 있다.(정수, 문자열, 불린, 리스트 객체등등)
mixed = ['jenny', 1, 1.4, True]
print(mixed)
list_of_lists = [['a', 1], ["b", 2]]
print(list_of_lists)
print(list_of_lists[1][1])


['jenny', 1, 1.4, True]
[['a', 1], ['b', 2]]
2


In [10]:
"""
Zero-indexing
"""
#인덱스: 리스트의 특정 아이템 위치를 나타내는 정수
#-list[index]:인덱스를 사용하여 리스트 내의 특정 아이템에 접근
# zero-indexing방식 : 0부터 시작한다.
# - list[0]:리스트의 첫 아이템

name = ['aaa', 'bbb', 'ccc', 'ddd']
print(name[0])
print(name[1])
print(name[2])
print(name[3])

#음수 인덱스 방식: 리스트의 마지막 아이템을 기준으로 인덱싱 -1 -2 -3 ~~
print(name[-1])
print(name[-2])
print(name[-3])
print(name[-4])

aaa
bbb
ccc
ddd
ddd
ccc
bbb
aaa


In [12]:
"""
List slicing
"""
#슬라이스: 리스트의 부분집합
#리스트 슬라이싱: 특정 인덱스 범위에 해당되는 슬라이스를 구하는 연산
#-사용법 List[1, 2, 3, 4, 5, 6] list[0:2] -> 1, 2
#리스트 아이템 수정: list[index] = new value


'\nList slicing\n'

In [14]:
"""
Multi-Dimensional Lists
"""
# 2차원 리스트 선언: List = [[sub_list1], [sub_list2]]
multi_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(multi_list[1][2])

# 2차원 리스트 아이템 수정:list[index][index] = new value


6


In [16]:
"""
Adding Lists Tgether
"""
items_one = [1, 2, 3]
items_two = [4, 5, 6]

total_item = items_one + items_two
print(total_item)

[1, 2, 3, 4, 5, 6]


In [2]:
"""
Useful Method for Lists
"""

#len(): 리스트 크기를 리턴
#count(): 특정 아이템의 개수를 리턴
#append(): 아이템을 리스트의 끝에추가
#insert(): 아이템을 리스트의 특정 위치에 추가
#pop():특정 위치의 아이템을 삭제
#remove(): 특정 아이템을 삭제
#sort(): 리스트 내 아이템들을 정렬
#sorted(): 정렬된 리스트를 리턴(원본 리스트를 건드리지 않고 싶을때 사용)
back = [2, 4, 3, 7, 10, 4]
size = len(back)
print(size)
count = back.count(4)
print(count)
back.append(1)
print(back)
back.insert(1, 1)
print(back)
back.pop(1)
print(back)
back.remove(1)
#back.remove(213)
back.sort()
print(back)

6
2
[2, 4, 3, 7, 10, 4, 1]
[2, 1, 4, 3, 7, 10, 4, 1]
[2, 4, 3, 7, 10, 4, 1]
[2, 3, 4, 4, 7, 10]


In [3]:
"""
lopps
"""
#반복문: 프로그램의 특정 부분을 반복적으로 실행하기 위한 제어문
#파이썬에서는 for whlie 키워드를 통해 반복문을 작성

#순차적
#제어문-if elif else
#반복문-for while

'\nlopps\n'

In [7]:
"""
for loops
"""
#for문:리스트의 아이템 마다 반복문을 실행한다.
#-> for A in B

nums =[1, 2, 3, 4, 5]

for num in nums:
    print(num)

#n 번 만큼 반복하고 싶을 땐? range(n)- n개의 정수들로 구성된 시르트를 반환(0, 1, 2, 3, 4, 5 ..., n-1)
#range()
for i in range(5):
    print(i)

1
2
3
4
5
0
1
2
3
4


In [10]:
"""
continue keyword
"""
#continue 키워드:남은 코드들을 건너뛰고 다음 반복을 시작한다.

nums = [1, 2, 3, 4, 5, 6]
for num in nums:
    if num % 2 == 0:
        continue
    print(num)

1
3
5


In [13]:
"""
break keyword
"""
#break 키워드: 실행중인 반복문 종료

game_play= ['stage1', 'stage2', 'stage3', 'gameover', 'stage4', 'stage5']

for play in game_play:
    
    if play == "gameover":
        print("gameover")
        break
    print(play + "is complete")

stage1is complete
stage2is complete
stage3is complete
gameover


In [1]:
"""
list comprehension
"""
#리스트 컴프리헨션: for문을 이용한 리스트 생성
#사용법: result = [expression for item in list]

for i in range(5):
    print(i)

arr = [i+1 for i in range(10)]
print(arr)

#리스트 컴프리헨션에 조건을 정의할 수 있다.

gamer = [['1', 'A'], ['2', 'B'], ['3', 'D']]
good_gamer = [player[0] for player in gamer if player[1] == 'A']
print(good_gamer)


0
1
2
3
4
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
['1']


In [2]:
"""
nested loops
"""
#중첩된 루프: 반복문안에 반복문이 있음
one_to_third = [i+1 for i in range(3)]
for i in one_to_third:
    for j in one_to_third:
        print("{} x {} = {}".format(i, j, i*j))

1 x 1 = 1
1 x 2 = 2
1 x 3 = 3
2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
3 x 1 = 3
3 x 2 = 6
3 x 3 = 9


In [3]:
"""
while loops
"""
#while문: 조건이 True일떄 반복 실행

"""
infinite loops
"""
#무한루프: 종료가 되지 않고 무한히 실행되는 경우 ->원인: while반복문 종료 조건이 없는경우

x = 1
y = 1
while y < 5:
    print("11")
    y += 1

11
11
11
11


In [4]:
"""
Function
"""
#프로그램의 함수: 어떤 기능을 수행하는 코드 집합 -> def fun_name(parameter):
#-주어진 입력x를 처리하여 출력을 반환한다.
#-특징: 이름에 의한 호출, 재사용성이 있음(len(), print(), range()'')
#대부분의 함수에는 입력이 필요하다.
#매개변수: 함수에 정의된 입력 변수
#인자:함수 호출 시의 입력 - 입력된 인자는 함수에 전달되어 매개변수의 값으로 할당

#함수의 입력이 많은경우 -키워드 인자: 함수 호출 시 매겨변수명과 인자 값을 같이 입력으로 제공-매개 변수 순서와 상관 없이 인자 전달가능
#                     -디플도 값: 함수에 정의된 매개변수의 기본값- 함수 호출 시 인자가 없어도 동작

def my_function(x):
    return x+1

print(my_function(1))

2


In [22]:
"""
Method
"""
#메서드:특정 클래스 내에 선언된 함수
#List.count(), List.append()

#객체지향 프로그래밍 - 클래스(정의) -속성(변수)
#                                - 행동(매서드)
#클래스를 만들었다면 인스턴스화 시켜야한다 인스턴스 == 객체
#지금 까지 배운 제어문:if, elif, else, for, while, function ->코드 블럭- 코드 블럭은 : 문자와 들여쓰기를 통해 구분
class my_class:
    def my_method(x):
        return x + 1
    
cls = my_class()

In [21]:
"""
Return Keyword
"""
#파이썬 함수에서는 여러개의 값을 반환하는 것이 가능하다.
#Lead year:윤년

def check_leap_year(year):
    if year % 4 == 0:
        return str(year) + "is a leap year"
    else:
        return str(year) + "is a not leap year"
    
result = check_leap_year(2020)
print(result)

2020is a leap year


In [25]:
"""
Global variables
"""
#변수의 선언위치에 따라 전역변수와 지역변수로 나눠진다.
#전역변수: 함수 밖에서 정의된 변수 - 함수 안/밖에서 모두 사용 가능하다
#지역변수: 함수 안에서만 사용이가능하다. 함수밖에서 사용불가
a = "hello"

def prints_a():
    print(a)
    

prints_a()  

hello


In [26]:
"""
Keyword Arguments
"""
def findvolume(height, width, depth): #def findvolume(height =1,width =2, depth =3): 
    print("height =" + str(height))
    print("width =" + str(width))
    print("depth =" + str(depth))
    return height + height + depth

print(findvolume(1, 2, 3))
print(findvolume(height =1,width =2, depth =3))

height =1
width =2
depth =3
5
height =1
width =2
depth =3
5


In [1]:
"""
NumPy
"""
#파이썬은 빠르지는 않고 코드생산성이 좋다 - 인터프리터 방식, 동적타입언어 이기 때문이다
#NumPy: 수치연산에 특화된 라이브러리 -다차원배열을 중심으로 한 다양한 수치계산을 위한 함수들을 제공
#                                 - 많은 부분이 C와Fortran으로 구현 -> 파이썬 기본 라이브러리보다 빠른 연산이 가능하다.
#패키지 설지:pip install numpy 
#패키지 사용하기: import numpy as np


'\nNumPy\n'

In [8]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [9]:
#리스트로부터 객체생성
lst = [1, 2, 3, 4]
arr = np.array(lst)
print(arr)

#파이썬 리스트: 서로다른 타입의 데이터 저장 가능, 각 데이터 아이템은 객체
#NumPy 배열:서로 다른타입의 데이터 저장 가능, 자료형 타입이 단일되면 고정된 타입의 배열로 처리한다 -> 즉 처리속도가 빨라지고 리스트보다 빨라짐
print(arr.dtype)

[1 2 3 4]
int32


In [10]:
"""
size comparison of ndarray and list object
"""
from sys import getsizeof

list = [1,2, 3, 4, 5, 6]
print(getsizeof(list)) # 56 -> 64 값과 주소를 동시에 저장

arr = np.array(list) #96 -> 100 값만 저장
print(getsizeof(arr))

104
128


In [11]:
"""
Operations with numpy array
"""
prices = [30, 25, 40, 20 ,20, 45, 50, 35]

new_pirces = [prices-5 for prices in prices]
print(new_prices)

prices_arr = np.array(prices)
prices_arr = prices_arr -5
print(prices_arr)


NameError: name 'new_prices' is not defined

In [12]:
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])
print(test_1)
print(test_2)
print(test_3)

test_3_fixed = test_3 +2
print(test_3_fixed)

total_grade = test_1+ test_2+test_3_fixed
print(total_grade)

final_grade = total_grade / 3
print(final_grade)

jeremy_test_2 = test_2[3]
print(jeremy_test_2 )

manual_adwoa_test_1 = np.array([test_1[1], test_1[2]])
print(manual_adwoa_test_1  )

student_scores = np.array([test_1,test_2,test_3])
print(student_scores)
print(student_scores[2][0])
print(student_scores[0:2][3])

[92 94 88 91 87]
[ 79 100  86  93  91]
[87 85 72 90 92]
[89 87 74 92 94]
[260 281 248 276 272]
[86.66666667 93.66666667 82.66666667 92.         90.66666667]
93
[94 88]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]
87


IndexError: index 3 is out of bounds for axis 0 with size 2

In [13]:
"""
배열 원소 단위의 논리 연산
"""
a = np.array([10, 2, 2, 4, 5, 3, 9, 8, 9, 7])
mask = a>5
print(mask)

#논리식을 만족하는 부분집합 구하기 =selection
selected = a[a > 5]
print(selected)
#논리식 결랍
selected = a[(a>6) | (a<4)]
print(selected)

[ True False False False False False  True  True  True  True]
[10  9  8  9  7]
[10  2  2  3  9  8  9  7]


In [14]:
"""
"""
#배열속성 지정: 배열의 크기, 형상(차원), 메모리 소비량, 데이터 타입을 결정
#배열 인덱싱: 배열의 개별 원소에 접근 및 값 할당
#배열 슬라이싱: 배열의 부분집합을 계산
#배열 재구조화:배열의 형상을 변경
#배열 결합 및 분할

#np.arange(start(옵션),stop*(필수),step(옵션)): 특정 범위의 정수 배열 생성
#-start:범위 시작값(포함), 디폴트:0
#-stop:범위 마지막값(제외)
#-step:간격, 디폴트값 1

'\n'

In [18]:
"""
"""
#난수 배열 생성하기
#-np.random.seed(num):똑같은 난수 배열 생성을 위한 시드 값
#-np.random.randint(high,size):정수로 구성된 난수 배열 생성

np.random.seed(0)
aww=np.random.randint(10, size= 2)
aww2=np.random.randint(10, size= (6,8))
print(aww2)

[[3 3 7 9]
 [3 5 2 4]
 [7 6 8 8]]


In [22]:
#Attributes

print(aww2)
print(aww2.ndim)
print(aww2.shape)#***중요
print(aww2.size)#***중요
print(aww2.dtype)#***중요
print(aww2.itemsize)
print(aww2.nbytes)

[[3 3 7 9]
 [3 5 2 4]
 [7 6 8 8]]
2
(3, 4)
12
int32
4
48


In [26]:
#배열 슬라이싱: 배열의 부분집합을 선택
#-arr[start:stop:step]
#다차원 배열 슬라이싱
#2차원 배열:arr[start1:stop1:step1, start2:stop2:step2]
np.random.seed(0)
aww2=np.random.randint(10, size= (6,8))
arr_sub = aww2[3:5,2:4]
print(arr_sub)
#배열 슬라이스는 복사복이 아닌 뷰 -> 배열 슬라이스 값을 변경하면 원본 배열 값도 변경된다.
np.random.seed(0)
aww2=np.random.randint(10, size= (6,8))
print(aww2)
arr_sub = aww2[:2,:2]
arr_sub[0][0] = 99
print(arr_sub)
print(aww2)

[[0 3]
 [3 3]]
[[5 0 3 3 7 9 3 5]
 [2 4 7 6 8 8 1 6]
 [7 7 8 1 5 9 8 9]
 [4 3 0 3 5 0 2 3]
 [8 1 3 3 3 7 0 1]
 [9 9 0 4 7 3 2 7]]
[[99  0]
 [ 2  4]]
[[99  0  3  3  7  9  3  5]
 [ 2  4  7  6  8  8  1  6]
 [ 7  7  8  1  5  9  8  9]
 [ 4  3  0  3  5  0  2  3]
 [ 8  1  3  3  3  7  0  1]
 [ 9  9  0  4  7  3  2  7]]


In [3]:
"""
"""
#유니버셜 함수:NumPy에서 제공하는 벡터화 연산 함수
#유연한 연산 제공: 스칼라-배열, 배열-배열, 다차원 배열등
#- 다차원 배열에 대한 원소 별 연산을 수행
#- 벡터화: 루프연산을 인터프리터 계층이 아닌 컴파일 계층에서 수행 -> 배열연산을 빠르게 처리
import numpy as np
big_array = np.random.randint(1, 100, size = 1000000)

# 주피터에서 제공하는 시간측정 함수
%timeit big_array

19.4 ns ± 0.201 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)


In [9]:
"""
numpy.ufunc
"""
np.random.seed(1)
arr1 = np.random.randint(10, size = 5)
arr2 = np.random.randint(10, size = 5)
print(arr1, arr2)
arr1 = arr1 - 2
print(arr1, arr2)

arr3 = arr1 + arr2
print(arr3)

arr4 = np.random.randint(10, size=(3,5))
print(arr4)

arr5 = arr4 ** 2
print(arr5)
#-유니버셜 함수의 벡터화 연산은 파이썬 루프로 구현된 연산보다 대부분 더 효율적이다.
#- 파이썬 반복문을 작성할 때 벡터화 연산으로 대체 가능한지 검토할 필요가 있다.

#배열의 사칙연산: 파이썬 기본 산술 연산자 또는 UFunc 사용
#arr1 = arr1 + 2 == np.add(arr1, 3)

[5 8 9 5 0] [0 1 7 6 9]
[ 3  6  7  3 -2] [0 1 7 6 9]
[ 3  7 14  9  7]
[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]
[[ 4 16 25  4 16]
 [ 4 16 49 49 81]
 [ 1 49  0 36 81]]


In [15]:
#np.abs():절대값 함수->파이썬에서 abs()을 기본으로 제공한다->백터화 연산
x = np.array([-2,-1, 0, 1, 2])
print(np.abs(x))

#np.linspce(start, stop, num(몇개의 구간으로나누는지)): 선형 간격의 벡터 생성 ->다양한 벡터/행렬 생성에 자주 사용된다.
x = np.linspace(0, 100, 5)
print(x)

#삼각함수: 데이터 과학에서 자주 사용되는 함수
#np.sin() 사인 함수
#np.cos() 코사인 함수
#np.tan() 탄젠트 함수
theta = np.linspace(0, np.pi, 3)
print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

x = np.linspace(0, 10)

[2 1 0 1 2]
[  0.  25.  50.  75. 100.]
[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [33]:
#데이터의 기술통계를 위한 집계함수 제공
#reduce():배열을 특정 연산으로 축소
x = np.arange(1, 5)
print(x)
agg = np.add.reduce(x)
agg2 = np.multiply.reduce(x)
print(agg)
print(x)
print(agg2)

#accumlate(): 계산의 중간 결과들을 배열으로 저장
accum = np.add.accumulate(x)
print(accum)

#배열 함계 게산:np.sum()->파이썬 내장함수 sum()보다 연산이 빠름
np.random.seed(3)
arr = np.random.rand(1000000) #rand(): 0~부터 값 생성
print(arr)
print("sum = ", np.sum(arr))
%timeit sum(arr)
%timeit np.sum(arr)

[1 2 3 4]
10
[1 2 3 4]
24
[ 1  3  6 10]
[0.5507979  0.70814782 0.29090474 ... 0.93033748 0.80429816 0.47400579]
sum =  500422.19897015305
62.6 ms ± 142 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
287 µs ± 406 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [41]:
print("max = ",np.max(arr))
print("min = ",np.min(arr))
print("mean = ",np.mean(arr))
print("median = ",np.median(arr))
print("percentile = ",np.percentile(arr, 90))

print(np.any(arr>1))
print(np.all(arr>0))

max =  0.9999996367889004
min =  1.5496004267534502e-06
mean =  0.500422198970153
median =  0.5005659265960778
percentile =  0.9001765340710965
False
True


In [44]:
#다차원 집계: 특정차원을 기준으로 집계 ->axis 
np.random.seed(5)
arr = np.random.randint(10, size = (3, 4))
print(arr)
print(np.sum(arr))
print(np.sum(arr, axis = 0))#axis = 0 -> 세로 axis = 1 ->가로
print(np.sum(arr, axis = 1))

[[3 6 6 0]
 [9 8 4 7]
 [0 0 7 1]]
51
[12 14 17  8]
[15 28  8]


In [5]:
"""
Casting
"""
import numpy as np
#데이터 타입 변경: 캐스팅
#브로드캐스팅: 다른 크기의 배열간 이항 연산을 수행하는 기능
#   - 유니버셜 함수에서 지원 ex)배열 - 스칼라 연산
# a = np.array([0, 1, 2]) a + 5 와  a = np.array([0, 1, 2]) b = np.array([5,5,5]) a + b dhk rkxek

#브로드캐스팅의 장점: 값 복제가 발생하지 않는다.

# a = np.ones((3, 3)) -> 3x3사이즈의 2차원 배열에 전부 1이 대입된다.
x = np.ones((3, 3))
print(x)
y = np.array(range(3))
print(y)
print( x + y)
#y의 shape를 확장하고 더한다

a = np.array(range(3))
print(a)
a = a[:, np.newaxis] # == a.reshpae((3,1))
print(a)
b = np.array(range(3))
print(b)
print(a +b)

#브로드캐스팅은 다음의 규칙들을 따름
# 규칙1: 두 배열의 차원수가 다른경우-> 더 적은 차원의 배열에 차원을 추가한다.

# 규칙2: 두 배열의 형상이 특정 차원에서 일치하지 않는경우 -> 해당 차원의 형상이 1인 배열을 다른 배열의 형상과 일치하도록 증가

# 규칙3: 임의의 차원에서 크기가 일치하지 않고 1도 아닌경우 -> 브로드캐스팅 불가


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[0 1 2]
[[0]
 [1]
 [2]]
[0 1 2]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [6]:
#배열에 대한 비교 연산 -> 부울 배열 출력
#부울배열(또는 마스크): 배열의 값을 추출, 수정, 계산, 조작할 때 사용
x = np.array(range(1,6))
print(x)
x < 3

[1 2 3 4 5]


array([ True,  True, False, False, False])

In [17]:
np.random.seed(0)
x = np.random.randint(10, size =(3, 4))
print(x)
print(x < 6)
#부울 배열을 이용한 연산: 원소 개수 세기 -Boolean의 정수표현 True = 1 False = 0
print(np.count_nonzero(x < 6)) # 부울 배열중에 True인 원소의 개수 출력
print(np.sum( x < 6))

print(np.any( x > 9)) #부울 배열중에 9보다 큰값이 있는가?
print(np.all( x > 1)) #부울 배열의 모든값이 1보다 큰가?

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[[ True  True  True  True]
 [False False  True  True]
 [ True  True False False]]
8
8
False
False


In [32]:
# 마스킹 연산: 부울 배열을 마스크로 사용하여 True를 만족하는 값들을 선택
np.random.seed(1)
x = np.random.randint(10, size=(3, 3))

print(x)
print(x[x<5])
print(np.std(x[x<5])) #표준편차
print(np.min(x[x<5])) #최소값
print(np.mean(x[x<5])) #평균값 출력
print(np.max(x[x<5])) #최대값


[[5 8 9]
 [5 0 0]
 [1 7 6]]
[0 0 1]
0.4714045207910317
0
0.3333333333333333
1


In [38]:
#지금까지 배운 배열 원소 접근 방법
#- 인덱싱(X[0]), 슬라이싱(X[2:4]), 마스킹 연산(X[X>4])

#펜시 인덱싱:한 번에 여러 배열 원소에 접근하는 방법
#- 단일 스칼라 대신 인덱스 배열을 전달
np.random.seed(3)
x = np.random.randint(100, size = 10)
print(x)
ind = [2, 3, 4]
print(x[ind])

[24  3 56 72  0 21 19 74 41 10]
[56 72  0]


In [45]:
np.random.seed(10)
x = np.random.randint(10, size = (3,5))
print(x)
row = [0, 1, 2]
col = [ 1, 3, 2]
#[0][1], [1][3], [2][2] 출력
print(x[row,col])

row  = np.array([0, 1, 2])
col  = np.array([2, 1, 4])

x = [row[:,np.newaxis], col]

[[9 4 0 1 9]
 [0 1 8 9 0]
 [8 6 4 3 0]]
[4 9 4]


In [ ]:
#numpy:수치연산에 최적화된 라이브러리 - 벡터화된 연산:코드 실행 속도 증가 및 메모리 절약

#브로드캐스팅: 다른 크기의 배열간 연산 가능 - 유니버설 함수를 더 쉽게 사용한다.

#마스킹연산: 부울 배열을 이용한 배열원소 접근

#팬시 인덱싱: 인덱스 배열을 이용한 배열 원소 접근