In [3]:
"""
print() function
"""

print("Hello World!")
print(100)
pi = 3.14
print(pi)

Hello World!
100
3.14


In [4]:
"""
asd
"""

my_name = "lee"
age = 23
my_email = "hamgame3@hs.ac.kr"


In [5]:
"""
Data Type: Integer
"""

value = 10
my_Phone = 2
my_book = 27

In [6]:
"""Data Type: Real Number"""

PI = 3.14
my_tall = 173.4
gold_price = 67502.96


In [9]:
"""
Data Type: String
"""
favorite_company = 'SamSung'
favorite_food = 'pasta'
favorite_carbrand = 'BMW'

print(favorite_company)
print(favorite_food)
print(favorite_carbrand)

print(favorite_company + favorite_food +favorite_carbrand)


SamSung
pasta
BMW
SamSungpastaBMW


In [8]:
"""
Exception Handling
"""

x = 1
try:
    print(y)
    print(x)

except:
    print("Error")
    
print("continue")

Error
continue


In [4]:
"""
List
"""
primes = [2, 3, 5, 7, 11, 11] #중복을 허용한다.
print(primes)
# 리스트 객체 초기화
none_list = []
print(none_list)

[2, 3, 5, 7, 11, 11]
[]


In [7]:
"""
Multiple different data type
"""
# 여러 데이터 타입의 아이템을 포함할 수 있다.(정수, 문자열, 불린, 리스트 객체등등)
mixed = ['jenny', 1, 1.4, True]
print(mixed)
list_of_lists = [['a', 1], ["b", 2]]
print(list_of_lists)
print(list_of_lists[1][1])


['jenny', 1, 1.4, True]
[['a', 1], ['b', 2]]
2


In [10]:
"""
Zero-indexing
"""
#인덱스: 리스트의 특정 아이템 위치를 나타내는 정수
#-list[index]:인덱스를 사용하여 리스트 내의 특정 아이템에 접근
# zero-indexing방식 : 0부터 시작한다.
# - list[0]:리스트의 첫 아이템

name = ['aaa', 'bbb', 'ccc', 'ddd']
print(name[0])
print(name[1])
print(name[2])
print(name[3])

#음수 인덱스 방식: 리스트의 마지막 아이템을 기준으로 인덱싱 -1 -2 -3 ~~
print(name[-1])
print(name[-2])
print(name[-3])
print(name[-4])

aaa
bbb
ccc
ddd
ddd
ccc
bbb
aaa


In [12]:
"""
List slicing
"""
#슬라이스: 리스트의 부분집합
#리스트 슬라이싱: 특정 인덱스 범위에 해당되는 슬라이스를 구하는 연산
#-사용법 List[1, 2, 3, 4, 5, 6] list[0:2] -> 1, 2
#리스트 아이템 수정: list[index] = new value


'\nList slicing\n'

In [14]:
"""
Multi-Dimensional Lists
"""
# 2차원 리스트 선언: List = [[sub_list1], [sub_list2]]
multi_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(multi_list[1][2])

# 2차원 리스트 아이템 수정:list[index][index] = new value


6


In [16]:
"""
Adding Lists Tgether
"""
items_one = [1, 2, 3]
items_two = [4, 5, 6]

total_item = items_one + items_two
print(total_item)

[1, 2, 3, 4, 5, 6]


In [2]:
"""
Useful Method for Lists
"""

#len(): 리스트 크기를 리턴
#count(): 특정 아이템의 개수를 리턴
#append(): 아이템을 리스트의 끝에추가
#insert(): 아이템을 리스트의 특정 위치에 추가
#pop():특정 위치의 아이템을 삭제
#remove(): 특정 아이템을 삭제
#sort(): 리스트 내 아이템들을 정렬
#sorted(): 정렬된 리스트를 리턴(원본 리스트를 건드리지 않고 싶을때 사용)
back = [2, 4, 3, 7, 10, 4]
size = len(back)
print(size)
count = back.count(4)
print(count)
back.append(1)
print(back)
back.insert(1, 1)
print(back)
back.pop(1)
print(back)
back.remove(1)
#back.remove(213)
back.sort()
print(back)

6
2
[2, 4, 3, 7, 10, 4, 1]
[2, 1, 4, 3, 7, 10, 4, 1]
[2, 4, 3, 7, 10, 4, 1]
[2, 3, 4, 4, 7, 10]


In [3]:
"""
lopps
"""
#반복문: 프로그램의 특정 부분을 반복적으로 실행하기 위한 제어문
#파이썬에서는 for whlie 키워드를 통해 반복문을 작성

#순차적
#제어문-if elif else
#반복문-for while

'\nlopps\n'

In [7]:
"""
for loops
"""
#for문:리스트의 아이템 마다 반복문을 실행한다.
#-> for A in B

nums =[1, 2, 3, 4, 5]

for num in nums:
    print(num)

#n 번 만큼 반복하고 싶을 땐? range(n)- n개의 정수들로 구성된 시르트를 반환(0, 1, 2, 3, 4, 5 ..., n-1)
#range()
for i in range(5):
    print(i)

1
2
3
4
5
0
1
2
3
4


In [10]:
"""
continue keyword
"""
#continue 키워드:남은 코드들을 건너뛰고 다음 반복을 시작한다.

nums = [1, 2, 3, 4, 5, 6]
for num in nums:
    if num % 2 == 0:
        continue
    print(num)

1
3
5


In [13]:
"""
break keyword
"""
#break 키워드: 실행중인 반복문 종료

game_play= ['stage1', 'stage2', 'stage3', 'gameover', 'stage4', 'stage5']

for play in game_play:
    
    if play == "gameover":
        print("gameover")
        break
    print(play + "is complete")

stage1is complete
stage2is complete
stage3is complete
gameover


In [1]:
"""
list comprehension
"""
#리스트 컴프리헨션: for문을 이용한 리스트 생성
#사용법: result = [expression for item in list]

for i in range(5):
    print(i)

arr = [i+1 for i in range(10)]
print(arr)

#리스트 컴프리헨션에 조건을 정의할 수 있다.

gamer = [['1', 'A'], ['2', 'B'], ['3', 'D']]
good_gamer = [player[0] for player in gamer if player[1] == 'A']
print(good_gamer)


0
1
2
3
4
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
['1']


In [2]:
"""
nested loops
"""
#중첩된 루프: 반복문안에 반복문이 있음
one_to_third = [i+1 for i in range(3)]
for i in one_to_third:
    for j in one_to_third:
        print("{} x {} = {}".format(i, j, i*j))

1 x 1 = 1
1 x 2 = 2
1 x 3 = 3
2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
3 x 1 = 3
3 x 2 = 6
3 x 3 = 9


In [3]:
"""
while loops
"""
#while문: 조건이 True일떄 반복 실행

"""
infinite loops
"""
#무한루프: 종료가 되지 않고 무한히 실행되는 경우 ->원인: while반복문 종료 조건이 없는경우

x = 1
y = 1
while y < 5:
    print("11")
    y += 1

11
11
11
11


In [4]:
"""
Function
"""
#프로그램의 함수: 어떤 기능을 수행하는 코드 집합 -> def fun_name(parameter):
#-주어진 입력x를 처리하여 출력을 반환한다.
#-특징: 이름에 의한 호출, 재사용성이 있음(len(), print(), range()'')
#대부분의 함수에는 입력이 필요하다.
#매개변수: 함수에 정의된 입력 변수
#인자:함수 호출 시의 입력 - 입력된 인자는 함수에 전달되어 매개변수의 값으로 할당

#함수의 입력이 많은경우 -키워드 인자: 함수 호출 시 매겨변수명과 인자 값을 같이 입력으로 제공-매개 변수 순서와 상관 없이 인자 전달가능
#                     -디플도 값: 함수에 정의된 매개변수의 기본값- 함수 호출 시 인자가 없어도 동작

def my_function(x):
    return x+1

print(my_function(1))

2


In [22]:
"""
Method
"""
#메서드:특정 클래스 내에 선언된 함수
#List.count(), List.append()

#객체지향 프로그래밍 - 클래스(정의) -속성(변수)
#                                - 행동(매서드)
#클래스를 만들었다면 인스턴스화 시켜야한다 인스턴스 == 객체
#지금 까지 배운 제어문:if, elif, else, for, while, function ->코드 블럭- 코드 블럭은 : 문자와 들여쓰기를 통해 구분
class my_class:
    def my_method(x):
        return x + 1
    
cls = my_class()

In [21]:
"""
Return Keyword
"""
#파이썬 함수에서는 여러개의 값을 반환하는 것이 가능하다.
#Lead year:윤년

def check_leap_year(year):
    if year % 4 == 0:
        return str(year) + "is a leap year"
    else:
        return str(year) + "is a not leap year"
    
result = check_leap_year(2020)
print(result)

2020is a leap year


In [25]:
"""
Global variables
"""
#변수의 선언위치에 따라 전역변수와 지역변수로 나눠진다.
#전역변수: 함수 밖에서 정의된 변수 - 함수 안/밖에서 모두 사용 가능하다
#지역변수: 함수 안에서만 사용이가능하다. 함수밖에서 사용불가
a = "hello"

def prints_a():
    print(a)
    

prints_a()  

hello


In [26]:
"""
Keyword Arguments
"""
def findvolume(height, width, depth): #def findvolume(height =1,width =2, depth =3): 
    print("height =" + str(height))
    print("width =" + str(width))
    print("depth =" + str(depth))
    return height + height + depth

print(findvolume(1, 2, 3))
print(findvolume(height =1,width =2, depth =3))

height =1
width =2
depth =3
5
height =1
width =2
depth =3
5


In [1]:
"""
NumPy
"""
#파이썬은 빠르지는 않고 코드생산성이 좋다 - 인터프리터 방식, 동적타입언어 이기 때문이다
#NumPy: 수치연산에 특화된 라이브러리 -다차원배열을 중심으로 한 다양한 수치계산을 위한 함수들을 제공
#                                 - 많은 부분이 C와Fortran으로 구현 -> 파이썬 기본 라이브러리보다 빠른 연산이 가능하다.
#패키지 설지:pip install numpy 
#패키지 사용하기: import numpy as np


'\nNumPy\n'

In [3]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [6]:
#리스트로부터 객체생성
lst = [1, 2, 3, 4]
arr = np.array(lst)
print(arr)

#파이썬 리스트: 서로다른 타입의 데이터 저장 가능, 각 데이터 아이템은 객체
#NumPy 배열:서로 다른타입의 데이터 저장 가능, 자료형 타입이 단일되면 고정된 타입의 배열로 처리한다 -> 즉 처리속도가 빨라지고 리스트보다 빨라짐
print(arr.dtype)

[1 2 3 4]
int32


In [10]:
"""
size comparison of ndarray and list object
"""
from sys import getsizeof

list = [1,2, 3, 4, 5, 6]
print(getsizeof(list)) # 56 -> 64 값과 주소를 동시에 저장

arr = np.array(list) #96 -> 100 값만 저장
print(getsizeof(arr))

104
128


In [14]:
"""
Operations with numpy array
"""
prices = [30, 25, 40, 20 ,20, 45, 50, 35]

new_pirces = [prices-5 for prices in prices]
print(new_prices)

prices_arr = np.array(prices)
prices_arr = prices_arr -5
print(prices_arr)


NameError: name 'new_prices' is not defined

In [27]:
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])
print(test_1)
print(test_2)
print(test_3)

test_3_fixed = test_3 +2
print(test_3_fixed)

total_grade = test_1+ test_2+test_3_fixed
print(total_grade)

final_grade = total_grade / 3
print(final_grade)

jeremy_test_2 = test_2[3]
print(jeremy_test_2 )

manual_adwoa_test_1 = np.array([test_1[1], test_1[2]])
print(manual_adwoa_test_1  )

student_scores = np.array([test_1,test_2,test_3])
print(student_scores)
print(student_scores[2][0])
print(student_scores[0:2][3])

[92 94 88 91 87]
[ 79 100  86  93  91]
[87 85 72 90 92]
[89 87 74 92 94]
[260 281 248 276 272]
[86.66666667 93.66666667 82.66666667 92.         90.66666667]
93
[94 88]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]
87


IndexError: index 3 is out of bounds for axis 0 with size 2

In [30]:
"""
배열 원소 단위의 논리 연산
"""
a = np.array([10, 2, 2, 4, 5, 3, 9, 8, 9, 7])
mask = a>5
print(mask)

#논리식을 만족하는 부분집합 구하기 =selection
selected = a[a > 5]
print(selected)
#논리식 결랍
selected = a[(a>6) | (a<4)]
print(selected)

[ True False False False False False  True  True  True  True]
[10  9  8  9  7]
[10  2  2  3  9  8  9  7]
